name: Production to render

on: 
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}